Download coding style tool without checking TLS certificate
As the Docker image of the CRI does not include a list of trusted root
certificates, the coding style tool, which is downloaded through HTTPS,
must be downloaded without a check of certificate.

diff --git a/tests/check_coding_style b/tests/check_coding_style
--- a/tests/check_coding_style
+++ b/tests/check_coding_style
@@ -10,7 +10,7 @@ cd "$(dirname "$0")"
 if [ ! -f "$TOOL_EXE" ];
 then
     echo Download tool...
-    wget "$TOOL_URL" -O "$TOOL_EXE" || { rm -f "$TOOL_EXE"; echo "Failed to download tool!"; exit 1; } 
+    wget -k "$TOOL_URL" -O "$TOOL_EXE" || { rm -f "$TOOL_EXE"; echo "Failed to download tool!"; exit 1; } 
     chmod +x "$TOOL_EXE"
 fi
 
